### ISSUE TITLE
Navigation events?

### ISSUE THREAD

**Issue by FluffyDiscord** [PlugFox/octopus#15]
Does this package expose any navigation events? Here an example use case:

I would like to pause a websocket connection when I navigate to another page, for example from A to B, and then resume when I go back from B to A.

Reading the package description makes me believe, that the page A would be still fully active even when I am on page B.

My current app architecture can get a little bit crazy, where I can have in stack/history page A > B > C1 > C2 > D. Simply, too deep, with same pages in navigation but with different construct params, but unfortunately this is needed.

**Comment by PlugFox** [comment]
You can do it with [NavigatorObserver](https://api.flutter.dev/flutter/widgets/NavigatorObserver-class.html) or [Guards](https://pub.dev/documentation/octopus/latest/octopus/OctopusGuard-class.html)
