### ISSUE TITLE
Add Support for `navigatorKey` in Octopus

### ISSUE THREAD

**Issue by yelmuratoff** [PlugFox/octopus#16]
### Title: Add Support for `navigatorKey` in Octopus

---

### Description

While the declarative approach of Octopus provides exceptional flexibility and control, there are cases where direct access to a `NavigatorState` is required. Currently, there is no built-in support for specifying a `navigatorKey`. This limitation can complicate scenarios involving:

- **Global navigation** from services or state management layers without direct access to `BuildContext`.
- **Advanced navigation patterns**, such as managing nested navigators or integrating with third-party tools requiring `NavigatorState`.

Although relying on a `navigatorKey` can conflict with the declarative principles of Octopus, offering it as an optional feature would expand the package's usability without forcing its use.

---

Introduce an optional `navigatorKey` parameter in the configuration of Octopus, allowing developers to:

1. Assign a `GlobalKey<NavigatorState>` to the root navigator or specific nested navigators.
2. Use this key for managing navigation globally when necessary.

Example:

```dart
final navigatorKey = GlobalKey<NavigatorState>();

Octopus(
  navigatorKey: navigatorKey,
  routes: Routes.values,
  defaultRoute: Routes.home,
);

**Comment by yelmuratoff** [comment]
Maybe I didn't notice something, but for cases where third-party packages and utilities need `NavigatorState` by receiving the navigatorKey or transferring it in general, then this cannot be done using this package.

**Comment by PlugFox** [comment]
@yelmuratoff, you should not use GlobalKey to receive NavigatorState.
Try using NavigatorObserver for this.

Just add a NavigatorObserver and receive a current state from the navigator getter.
That approach is much safer than a GlobalKey.

https://api.flutter.dev/flutter/widgets/NavigatorObserver/navigator.html

**Comment by yelmuratoff** [comment]
@PlugFox 
Thanks for the quick reply, I'll take a look.
