### ISSUE TITLE
How to replace first route

### ISSUE THREAD

**Issue by FluffyDiscord** [PlugFox/octopus#17]
I have first route Login, and I want to redirect to Home and remove the Login from history, so user cannot go back.

Using `context.octopus.pop()` and `context.octopus.push()` closes the app, which I guess is expected.

How to I simply replace the route and prevent going back, or do I need to use the `WillPop` widget on the Home screen?

**Comment by PlugFox** [comment]
@FluffyDiscord you can do everything with [setState](https://pub.dev/documentation/octopus/latest/octopus/Octopus/setState.html) where you can change current navigation stack.
Moreover, almost every method work through this.

**Comment by FluffyDiscord** [comment]
Right, will look at that, thanks
