### ISSUE TITLE
Проблема с изменением стейта авторизации, из-за чего не срабатывает гуард (?)

### ISSUE THREAD

**Issue by demkogit** [PlugFox/octopus#19]
Взял код из примера. В нем поменял AuthenticationController (убрал control). После чего (например для signOut) гуард выполняет метод call только один раз, но в стейт попадает сначала AuthenticationState.processing, потом AuthenticationState.idle из репозитория

<details>
  <summary>код измененного AuthenticationController</summary>

  ```
final class AuthenticationController extends ChangeNotifier
    implements ValueListenable<AuthenticationState> {
  AuthenticationController({
    required IAuthenticationRepository repository,
    AuthenticationState initialState =
        const AuthenticationState.idle(user: User.unauthenticated()),
  })  : _repository = repository,
        state = initialState {
    _userSubscription = repository
        .userChanges()
        .map<AuthenticationState>((u) => AuthenticationState.idle(user: u))
        .where((newState) =>
            state.isProcessing || !identical(newState.user, state.user))
        .listen(setState, cancelOnError: false);
  }

  AuthenticationState state = const AuthenticationState.idle(
    user: User.unauthenticated(),
  );

  final IAuthenticationRepository _repository;
  StreamSubscription<AuthenticationState>? _userSubscription;

  @override
  AuthenticationState get value => state;

  void setState(AuthenticationState newState) {
    state = newState;
    debugPrint('newState: $newState');
    notifyListeners();
  }

  /// Restore the session from the cache.
  Future<void> restore() async {
    setState(
      AuthenticationState.processing(
        user: state.user,
        message: 'Restoring session...',
      ),
    );
    await _repository.restore();
  }

  /// Sign in with the given [data].
  Future<void> signIn(SignInData data) async {
    setState(
      AuthenticationState.processing(
        user: state.user,
        message: 'Logging in...',
      ),
    );
    await _repository.signIn(data);
  }

  /// Sign out.
  Future<void> signOut() async {
    setState(
      AuthenticationState.processing(
        user: state.user,
        message: 'Logging out...',
      ),
    );
    // так сработает
    // await Future<void>.delayed(Duration.zero); 
    await _repository.signOut();
  }

  @override
  void dispose() {
    _userSubscription?.cancel();
    super.dispose();
  }
}
  ```
</details>

В принте выводятся стейты в ожидаемой последовательности, но в данном случае гуард срабатывает только на первый setState

Скорее всего это не баг, а асинхронный прикол. Просто я уже много времени потратил на то, чтобы понять, почему ломается, но так и не понял

**Comment by PlugFox** [comment]
@demkogit я крайне не рекомендую делать асинхронные гарды и навигацию.
Это очень сложно управляемая и непредсказуемая штука.

Оно сейчас существует только потому, что кто то без этого не сможет обойтись.

Сейчас это реализовано через очередь (мьютекс) и все изменения стараются происходить строго по очереди, но опять же, проще простого тут выстрелить себе в ногу.
Потому что у тебя разные источники могут мутировать навигацию одновременно и в тоже время изменения могут происходить на стороне самой платформы.

Надеюсь в будущем у меня получиться найти решение таким проблемам и провести масштабный рефакторинг.
